### ISSUE TITLE
Still crashing on all services on fresh/clean install.

### ISSUE THREAD

**Issue by slushieken** [testdasi/grafana-unraid-stack#16]
I saw an update was made Nov 21 - but this is still crashing on a fresh install.

Hoping that maybe we can get some momentum going to bring this back to life.

> [info] Initialisation started...
> [info] influxdb fixed.
> [info] loki fixed.
> [info] telegraf fixed.
> [info] promtail fixed.
> [info] grafana fixed.
> [info] Initialisation complete
> 
> [info] Runing apps...
> [info] Run influxdb as service on port 8086
> Executable /usr/bin/influxd does not exist!
> [info] Run loki as daemon on port 3100
> [info] Run telegraf as service
> [info] Run promtail as daemon on port 9086
> [info] Run grafana as service on port 3006
>  * Starting Grafana Server
>    ...fail!
> [info] All done
> 
> [error] influxdb crashed!
> [info] loki PID: 60
> [info] Skip hddtemp due to USE_HDDTEMP set to no
> [error] telegraf crashed!
> [info] promtail PID: 76
> [error] grafana crashed!

My appreciation to the maintainer. After spending a few days trying to get this going myself, and finding no other working versions, I know it is difficult to sync up all the versions to run without crashing in a single container.

FYI I don't think it will matter but this was on Unraid Version 6.12.4 2023-08-31.

**Comment by negadin** [comment]
Similar error here, also 6.12.4. 

[info] Initialisation started...
[info] influxdb fixed.
[info] loki fixed.
[info] telegraf fixed.
[info] promtail fixed.
[info] grafana fixed.
[info] Initialisation complete

[info] Runing apps...
[info] Run influxdb as service on port 8086
Executable /usr/bin/influxd does not exist!
[info] Run loki as daemon on port 3100
[info] Run telegraf as service
[info] Run promtail as daemon on port 9086
[info] Run grafana as service on port 3006
 * Starting Grafana Server
   ...fail!
[info] All done

[error] influxdb crashed!
[info] loki PID: 60
[info] Skip hddtemp due to USE_HDDTEMP set to no
[error] telegraf crashed!
[info] promtail PID: 77
[error] grafana crashed!

**Comment by The-Padi** [comment]
Same for me on 6.12.6 :
```
[info] Initialisation started...
[info] influxdb fixed.
[info] loki fixed.
[info] telegraf fixed.
[info] promtail fixed.
[info] grafana fixed.
[info] Initialisation complete

[info] Runing apps...
[info] Run influxdb as service on port 8086
Executable /usr/bin/influxd does not exist!
[info] Run loki as daemon on port 3100
[info] Run telegraf as service
[info] Run promtail as daemon on port 9086
[info] Run grafana as service on port 3006
 * Starting Grafana Server
   ...fail!
[info] All done

[error] influxdb crashed!
[info] loki PID: 60
[info] Skip hddtemp due to USE_HDDTEMP set to no
[error] telegraf crashed!
[info] promtail PID: 77
[error] grafana crashed!
```

**Comment by visigoth** [comment]
i am running into the same issue. i tried installing the influxdb package manually in the container and i ran into the following errors:

```
W: https://packages.grafana.com/oss/deb/dists/stable/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: GPG error: https://repos.influxdata.com/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D8FF8E1F7DF8B07E
E: The repository 'https://repos.influxdata.com/ubuntu focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

i'm surprised the docker build succeeded. it seems that `install-influxdb-telegraf.sh` does not exit on the failure at `apt -y update && apt -y install telegraf influxdb`. the other scripts similarly won't fail on errors.

**Comment by visigoth** [comment]
https://repos.influxdata.com/ubuntu/ mentions that influxdb.key is deprecated and that influxdata-archive.key is the correct key to use on modern distributions.

**Comment by visigoth** [comment]
i've created https://github.com/visigoth/grafana-unraid-stack-base with a fix to import the correct key, and i've published the full image at docker.io/visigoth/grafana-unraid-stack. i now get a message that grafana has crashed in the docker log. however, opening the webui works and it seems to be working with live data.

```
[info] Initialisation started...
[info] influxdb fixed.
[info] loki fixed.
[info] telegraf fixed.
[info] promtail fixed.
[info] grafana fixed.
[info] Initialisation complete

[info] Runing apps...
[info] Run influxdb as service on port 8086
Starting influxdb...
influxdb process was started [ OK ]
[info] Run loki as daemon on port 3100
[info] Run telegraf as service
Starting the process telegraf [ OK ]
telegraf process was started [ OK ]
[info] Run promtail as daemon on port 9086
[info] Run grafana as service on port 3006
 * Starting Grafana Server
   ...fail!
[info] All done

[info] influxdb PID: 65
[info] loki PID: 84
[info] Skip hddtemp due to USE_HDDTEMP set to no
[info] telegraf PID: 98
[info] promtail PID: 104
[error] grafana crashed!
```

**Comment by DanielCalverley** [comment]
+1

[info] Initialisation started...
[info] influxdb fixed.
[info] loki fixed.
[info] telegraf fixed.
[info] promtail fixed.
[info] grafana fixed.
[info] Initialisation complete

[info] Runing apps...
[info] Run influxdb as service on port 8086
Executable /usr/bin/influxd does not exist!
[info] Run loki as daemon on port 3100
[info] Run telegraf as service
[info] Run promtail as daemon on port 9086
[info] Run grafana as service on port 3006
 * Starting Grafana Server
   ...fail!
[info] All done

[error] influxdb crashed!
[info] loki PID: 60
[info] Skip hddtemp due to USE_HDDTEMP set to no
[error] telegraf crashed!
[info] promtail PID: 77
[error] grafana crashed!

**Comment by nixmomo** [comment]
This is still not fixed right? 
I get on a fresh install 
[error] influxdb crashed!
[info] loki PID: 60
[info] Skip hddtemp due to USE_HDDTEMP set to no
[error] telegraf crashed!
[info] promtail PID: 77
[error] grafana crashed!

Grafana itself is working but has no data because connection to influxdb is not possible

**Comment by Nenzyz** [comment]
Please try this image `nenzyz/grafana-unraid-stack` I've rebuilt it from the same author's repositories with proper influxdb installation, there is an issue with gpg keys. Mine is working fine.

**Comment by McGeaverBeaver** [comment]
I'm a bit confused. How is this still broken but the container is updated every few days? Who's maintaining this? Why is it not removed from the  Unraid App store if it's not broken?? 

https://registry.hub.docker.com/r/testdasi/grafana-unraid-stack/tags

**Comment by dmcosta** [comment]
Yep, fresh install today, and It crashes on all services.

[info] Initialisation started...
[info] influxdb fixed.
[info] loki fixed.
[info] telegraf fixed.
[info] promtail fixed.
[info] grafana fixed.
[info] Initialisation complete

[info] Runing apps...
[info] Run influxdb as service on port 8086
Executable /usr/bin/influxd does not exist!
[info] Run loki as daemon on port 3100
[info] Run telegraf as service
[info] Run promtail as daemon on port 9086
[info] Run grafana as service on port 3006
 * Starting Grafana Server
   ...fail!
[info] All done

[error] influxdb crashed!
[error] loki crashed!
[info] Skip hddtemp due to USE_HDDTEMP set to no
[error] telegraf crashed!
[info] promtail PID: 77
[error] grafana crashed!

**Comment by Korvenwin** [comment]
I'm having same issue.

**Comment by Guruleenyc** [comment]
What they said! Same issues here. Is this proj. not being supported anymore?

**Comment by teaalltr** [comment]
Guys just use https://github.com/testdasi/grafana-unraid-stack/issues/16#issuecomment-2109434376, works a treat!
Thank you @Nenzyz !

**Comment by RichardUUU** [comment]
I tried grafana years ago and have finally come back to see if the experience was any better. Nope.
Just tried it with `nenzyz/grafana-unraid-stack`
```
[info] influxdb PID: 66
[error] loki crashed!
[info] Skip hddtemp due to USE_HDDTEMP set to no
[info] telegraf PID: 96
[info] promtail PID: 101
[error] grafana crashed!
```

**Comment by Nenzyz** [comment]
> I tried grafana years ago and have finally come back to see if the experience was any better. Nope. Just tried it with `nenzyz/grafana-unraid-stack`
> 
> ```
> [info] influxdb PID: 66
> [error] loki crashed!
> [info] Skip hddtemp due to USE_HDDTEMP set to no
> [info] telegraf PID: 96
> [info] promtail PID: 101
> [error] grafana crashed!
> ```

According to log output, we can see the influxdb is started properly, I would check in details why grafana is crashing.

**Comment by skalec** [comment]
> Guys just use [#16 (comment)](https://github.com/testdasi/grafana-unraid-stack/issues/16#issuecomment-2109434376), works a treat! Thank you [@Nenzyz](https://github.com/Nenzyz) !

Dont work.  I use testdasi/grafana-unraid-stack:stable-amd64 and all fine

**Comment by notloged** [comment]
&gt; &gt; Guys just use [#16 (comment)](https://github.com/testdasi/grafana-unraid-stack/issues/16#issuecomment-2109434376), works a treat! Thank you [@Nenzyz](https://github.com/Nenzyz) !
&gt; 
&gt; Dont work. I use testdasi/grafana-unraid-stack:stable-amd64 and all fine

Thank you very much! Works perfectly
